### ISSUE TITLE
Ability to hide server list

### ISSUE THREAD

**Issue by mikrobyte** [thelounge/thelounge.github.io#47] opened 2016-11-29 12:34 UTC
**This is not an issue** _but a "nice to have" feature._

The ability to hide the server's list on the left, the same way we can hide the nicknames list on the right.

**Comment by astorije** [comment] 2016-12-01 05:46
Closing as duplicate of https://github.com/thelounge/lounge/issues/50, but thanks for your input!

**Closed by astorije** 2016-12-01 05:46 UTC
