### ISSUE TITLE
install.md: Instructions invalid for Debian

### ISSUE THREAD

**Issue by CuleX** [thelounge/thelounge.github.io#48] opened 2016-11-30 09:47 UTC
In `_docs/getting_started/install.md`, the section titled "Ubuntu / Debian" suggests using `sudo apt-get -y install nodejs-legacy npm`.

On Debian stable, [nodejs == nodejs-legacy, which is version 0.10.29](https://packages.debian.org/search?keywords=nodejs). Lounge does not run on node 0.10.29. This does not affect Debian testing, where nodejs-legacy is 4.x (4.6.1 right now) and is thus usable.

The instructions for Debian stable should recommend manually installing node 4.x (or above? Not sure how far up it goes).

**Comment by astorije** [comment] 2016-12-01 05:37
Indeed, we dropped support of Node < v4 when releasing The Lounge v2.0.0.
We should probably remove the install command for Node from our docs, and instead link to more official documentation for this. Also, we are [really close from having a dedicated Debian package](https://github.com/thelounge/deb-lounge/pull/1), so there is that.

**Comment by YaManicKill** [comment] 2016-12-01 10:35
> We should probably remove the install command for Node from our docs, and instead link to more official documentation for this.

Agreed, essentially all of the documentation o nthat page is "How to install node", which we should delegate to the official docs for node. They will do a much better job than us.

**Comment by astorije** [comment] 2016-12-08 07:18
@maxpoulin64, should our documentation on how to install Node on Debian/Ubuntu recommend "Install Node the way you want + run `npm install -g thelounge`" or make use of https://github.com/thelounge/deb-lounge ?
I feel like the latter is much nicer, especially since it runs as a daemon as well!

I can update the documentation myself if you're busy, but I could use some help listing the steps to get there :) Thanks!

**Comment by maxpoulin64** [comment] 2016-12-08 07:23
@astorije It makes a lot more sense to use the debs yeah. Just need to build and host said debs, of course. It's useless if we have people manually build the .deb and install it, might as well just use npm in that situation.

I can build them quickly for the latest version of you need, or we can have Travis build them I guess.

**Comment by astorije** [comment] 2016-12-08 07:40
This ticket is actually a duplicate of #25 so I'm closing it as dup, but I want to continue the discussion of documenting the debs on the website.

Feel free to add details/convo here or open a new ticket.

Also, addressed this very issue in #49, at least until we document the debs (because right now following the steps on the website just doesn't work, which is bad!).

**Closed by astorije** 2016-12-08 07:40 UTC
Labels: bug

**Comment by astorije** [comment] 2016-12-08 07:44
@maxpoulin64, 100% agree with you.

I'm all for setting up Travis CI to do that for us and not worry about it. Question then would be: where do we host the debs? Is there a typical way/place to do this?
If not, we could always use GitHub's feature to attach binaries to a release (like at the bottom of https://github.com/thelounge/lounge/releases/tag/v2.1.0), does that seem like a reasonable idea?

I'm fairly incompetent when it comes to that for now, so don't be offended at what I write :D Any input is welcome.

**Comment by YaManicKill** [comment] 2016-12-08 08:03
It's pretty common nowadays to just stick your binaries on github. I think that's fine.

**Comment by astorije** [comment] 2016-12-09 03:24
> It's pretty common nowadays to just stick your binaries on github. I think that's fine.

Real question is, if we do that, is it still convenient to use things like `apt-get install ...` (through a custom apt repository I'm guessing) or not? Again, fairly inexperienced with this side of package management on Linux so forgive me if I'm asking dumb questions :)

**Comment by maxpoulin64** [comment] 2016-12-09 03:26
Ideally we'd want a custom repo, but that's a bit more of a pain to manage than just GitHub releases. I don't think we can host debian repos, even on GitHub pages, but we'd have to look into that. Using the releases would be a great start at least (not exactly apt-get, but `dpkg -i ...` is already pretty good, or in many distros just double-click and install).

**Comment by astorije** [comment] 2016-12-09 06:04
Sounds good! We can start with `dpkg -i ...` and see later for repos/`apt-get`.

What do you think of the following in terms of plan:
- Build `.deb` files for all 3 releases since v2 (because why not)
- Attach them to GitHub releases in the `lounge` repo
- Document that in this current repo (what are the steps? Just `dpkg -i xxx.deb`?)
- Set up Travis CI to do it for us as of next release (unless we release before coming up with this)

The last one is a nice-to-have, but I think having a deb v2.1.0 + correct documentation for it is more important to start with :)
I'm guessing one needs to run it from a Debian distro to produce a proper `.deb`? Mind sending me the binaries when you have a moment?

I actually managed to always use `apt-get` for software I use and never run `dpkg -i`, how would one run an upgrade when we release a new version?

**Comment by YaManicKill** [comment] 2016-12-09 08:09
> Real question is, if we do that, is it still convenient to use things like apt-get install
